In [163]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import datetime as dt

import seaborn as sns
sns.set_style('darkgrid')

%matplotlib inline
#%load_ext watermark
#%watermark

In [164]:
#load csv data

path = lambda X: f'/home/charles/Laufer/Lobster_embryo_scripts/Lobster_embryo_2017_{X}_data .csv'
data = lambda X: pd.read_csv(path(X))
trials = ['BPA', 'C3', 'Control']

BPA, C3, Control = list(map(data, trials))

BPA.head()

,Tray,Cube,S3_date,SurvivED,Trial,Start_date,Lobster,Most_recent_date,Concentration,days_to_S3
0,T1,1,2017-07-27,T,BPA,2017-07-08,L9,2017-07-27,3,19.0
1,T1,2,NaN,E,BPA,2017-07-08,L9,2017-07-27,3,NaN
2,T1,3,2017-07-27,T,BPA,2017-07-08,L9,2017-07-27,3,19.0
3,T1,4,NaN,E,BPA,2017-07-08,L9,2017-07-27,3,NaN
4,T1,5,NaN,E,BPA,2017-07-08,L9,2017-07-27,3,NaN